# Generated by Django 6.0.7 on 2026-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paltín', max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('human_notification_phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_connected_phone', models.CharField(blank=True, max_length=30)),
                ('ai_provider', models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('chatgpt', 'ChatGPT (OpenAI)'), ('gemini', 'Gemini (Google)')], default='claude', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
