# Generated by Django 4.2.11 on 2026-09-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_add_whatsapp_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keyword', models.CharField(help_text='Palabra o intención clave', max_length=150)),
                ('response_text', models.TextField(help_text='Respuesta que enviará el agente')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
