# Generated by Django 4.2.11 on 2026-09-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_whatsappflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='enable_loyalty',
            field=models.BooleanField(default=True, help_text='Permitir consultar puntos de fidelidad'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='enable_sales',
            field=models.BooleanField(default=True, help_text='Permitir ventas automáticas de la IA'),
        ),
    ]
