# Generated by Django 4.2.11 on 2026-09-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_agentconfig_enable_loyalty_agentconfig_enable_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappflow',
            name='response_text',
        ),
        migrations.AddField(
            model_name='whatsappflow',
            name='edges',
            field=models.JSONField(blank=True, default=list, help_text='Configuración de Canvas Conexiones'),
        ),
        migrations.AddField(
            model_name='whatsappflow',
            name='name',
            field=models.CharField(default='Nuevo Flujo', help_text='Nombre del Flujo', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappflow',
            name='nodes',
            field=models.JSONField(blank=True, default=list, help_text='Configuración de Canvas Nodos'),
        ),
    ]
