# Generated by Django 6.0.7 on 2026-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('delivery_type', models.CharField(choices=[('despacho', 'Despacho a domicilio'), ('retiro', 'Retiro en local')], default='retiro', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_commune', models.CharField(blank=True, max_length=100)),
                ('delivery_reference', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('mercadopago', 'MercadoPago')], default='efectivo', max_length=20)),
                ('payment_condition', models.CharField(choices=[('inmediato', 'Inmediato'), ('plazo', 'A Plazo')], default='inmediato', max_length=20)),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=200)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=200)),
                ('mercadopago_link', models.URLField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('delivery_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('points_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
        ),
    ]
