# Generated by Django 4.2.11 on 2026-09-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_update_margins_from_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcialmente_entregado', 'Parcialmente Entregado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcialmente_entregado', 'Parcialmente Entregado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=25),
        ),
    ]
