# Generated by Django 6.0.7 on 2026-08-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('palta', 'Palta'), ('huevo', 'Huevo'), ('otro', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('unidad', 'Unidad'), ('kilo', 'Kilo'), ('docena', 'Docena'), ('caja', 'Caja')], default='unidad', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default='Proveedor', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=0, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='products.product')),
            ],
        ),
    ]
