# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_update_bundle_stock_and_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_be_sold',
            field=models.BooleanField(default=True, help_text='Si es falso, no aparecerá en el menú de ventas'),
        ),
    ]
