# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_can_be_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_multiplier',
            field=models.DecimalField(decimal_places=0, default=1, help_text='Multiplica unidades al comprar', max_digits=10),
        ),
    ]
