# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_purchase_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
