# Generated by Django 4.2.11 on 2026-09-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcomponent_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('abono', 'Abono'), ('pagado', 'Pagado')], default='pagado', max_length=20),
        ),
    ]
