# Generated by Django 4.2.11 on 2026-09-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcategory_alter_product_product_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bundle'], name='products_pr_is_bund_f113db_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['can_be_sold'], name='products_pr_can_be__410971_idx'),
        ),
    ]
