# Generated by Django 6.0.7 on 2026-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('category', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra de insumos'), ('gasto_operacional', 'Gasto operacional'), ('despacho', 'Despacho'), ('marketing', 'Marketing'), ('otro', 'Otro')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.CharField(max_length=300)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
