# Generated by Django 6.0.7 on 2026-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra de insumos'), ('gasto_operacional', 'Gasto operacional'), ('combustible', 'Combustible'), ('cajas', 'Cajas / Embalaje'), ('despacho', 'Despacho'), ('marketing', 'Marketing'), ('otro', 'Otro')], max_length=30),
        ),
    ]
