# Generated by Django 4.2.11 on 2026-09-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Empresa Demo', max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('account_rut', models.CharField(blank=True, max_length=20)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('account_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
