# Generated by Django 6.0.7 on 2026-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('palta', 'Solo Palta'), ('huevo', 'Solo Huevo'), ('ambos', 'Palta + Huevo'), ('proteina', 'Alta Proteína'), ('fit', 'Fit y Saludable'), ('familiar', 'Familiar'), ('especial', 'Ocasiones Especiales')], max_length=20)),
                ('meal_type', models.CharField(choices=[('desayuno', 'Desayuno'), ('entrada', 'Entrada'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack'), ('postre', 'Postre')], max_length=20)),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('avanzada', 'Avanzada')], default='facil', max_length=20)),
                ('prep_time_minutes', models.IntegerField(default=15)),
                ('cook_time_minutes', models.IntegerField(default=20)),
                ('servings', models.IntegerField(default=2)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('tips', models.TextField(blank=True)),
                ('calories', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('proteins_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('fats_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('fiber_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('vitamins_info', models.TextField(blank=True)),
                ('health_benefits', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
